sudo: required
services:
  - docker

before_install:
  - docker build -t rjpdeen/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rjpdeen/react-test npm test -- --coverage

after_success:
  - docker build -t rjpdeen/multi-client ./client
  - docker build -t rjpdeen/multi-nginx ./nginx
  - docker build -t rjpdeen/multi-server ./server
  - docker build -t rjpdeen/multi-worker ./worker

  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push the to Docker Hub
  - docker push rjpdeen/multi-client
  - docker push rjpdeen/multi-nginx
  - docker push rjpdeen/multi-server
  - docker push rjpdeen/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-916503846740"
  bucket_path: "docker-multi"

  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"